/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author JoseAdolfo
 */
public class GUI_InformacionAuto extends javax.swing.JPanel {

    /**
     * Creates new form InformacionAuto
     */
    public GUI_InformacionAuto() {
        initComponents();
    }
    public void limpiar()
    {
        this.jt_Cedula.setText("");
        this.jt_Nombre.setText("");
        this.jt_NumRegistro.setText("");
        this.jt_Placa.setText("");
    }
    
    public void estadoInicial()
    {
        this.jt_NumRegistro.setEnabled(true);
        this.jt_Nombre.setEnabled(false);
        this.jt_Cedula.setEnabled(false);
        this.jt_Placa.setEnabled(false);
    }
    public void estadoAgregar()
    {
        this.jt_NumRegistro.setEnabled(false);
        this.jt_Nombre.setEnabled(true);
        this.jt_Cedula.setEnabled(true);
        this.jt_Placa.setEnabled(true);
    }
    public void estadoModificar()
    {
        this.jt_NumRegistro.setEnabled(false);
        this.jt_Nombre.setEnabled(true);
        this.jt_Cedula.setEnabled(true);
        this.jt_Placa.setEnabled(true);
    }
    
    public String devolverNumeroRegistro()
    {
        return this.jt_NumRegistro.getText();
        
    }
    
    public String[] devolverInformacion()
    {
        String arreglo[]=new String [4];
        arreglo[0]=jt_NumRegistro.getText();
        arreglo[1]=jt_Nombre.getText();
        arreglo[2]=jt_Cedula.getText();
        arreglo[3]=jt_Placa.getText();
        return arreglo;
    }
    
    public void mostrarInformacion(String [] arregloMostrar)
    {
        String[] arreglo = arregloMostrar;
        jt_NumRegistro.setText(arreglo[0]);
        jt_Nombre.setText(arreglo[1]);
        jt_Cedula.setText(arreglo[2]);
        jt_Placa.setText(arreglo[3]);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NumRegistro = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Cedula = new javax.swing.JLabel();
        jl_Placa = new javax.swing.JLabel();
        jt_NumRegistro = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Cedula = new javax.swing.JTextField();
        jt_Placa = new javax.swing.JTextField();

        jl_NumRegistro.setText("Numero de Registro");

        jl_Nombre.setText("Nombre del Dueño");

        jl_Cedula.setText("Cédula del Dueño");

        jl_Placa.setText("Placa del Auto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Cedula)
                            .addComponent(jl_Nombre)
                            .addComponent(jl_Placa))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_Nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jt_Cedula, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jt_Placa, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_NumRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jt_NumRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NumRegistro)
                    .addComponent(jt_NumRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cedula)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Placa)
                    .addComponent(jt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_NumRegistro;
    private javax.swing.JLabel jl_Placa;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_NumRegistro;
    private javax.swing.JTextField jt_Placa;
    // End of variables declaration//GEN-END:variables
}
